name: update stars

on:
  push:
  schedule:
    - cron: '*/10 * * * *'
  watch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: update
        env: 
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPO_NAME: ${{ github.repository }}
        run: |
          STAR_COUNT=$(curl -s https://api.github.com/repos/$REPO_NAME | jq '.stargazers_count') &&
            if [ $STAR_COUNT != null ]; then hub api repos/$REPO_NAME --raw-field name=this-repo-has-$STAR_COUNT-stars > /dev/null; fi
